### ISSUE TITLE
Enable or disable mods

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#219]
# Tasks

- [ ] Add field to the config
- [ ] Implement disabling when upgrading
- [ ] Configure interactively or using CLI options

---

## The problem

There is no way to temporarily remove a mod.

## My solutions

A `ferium remove`-like menu where mods can be enabled or disabled. The disabled mods will still be downloaded, but will be suffixed with a `.disabled` file extension. This will make ferium compatible with MultiMC and PrismMC.

**Comment by xrtxn** [comment]
How should it work? Should it just disable the mods and if the user upgrades check the filename and if it exists with the extension .disabled not update? That makes sense to me.

**Comment by theRookieCoder** [comment]
Yup, I plan on just checking if there is a `.disabled` extension

**Comment by xrtxn** [comment]
It doesn't look too difficult I think I can take a look at it.

**Comment by xrtxn** [comment]
Should we store the mod filenames locally? Because if we don't the command can only run when the user has internet connection...

**Comment by ok-coder1** [comment]
Is this fixed? Well now `ferium` knows which mod is which if you run `ferium scan` so shouldn't this problem be fixed?

**Comment by theRookieCoder** [comment]
This feature needs #140
