### ISSUE TITLE
Remove mods by their slugs

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#439]
# Tasks

- [ ] Store the slug when adding a mod
- [ ] Fetch the slugs and update the config when listing verbosely to allow older configs to take advantage of this feature
- [ ] Implement removal by slug in the remove command

---

## The Problem

We can currently remove mods by their names or IDs, but not by their slugs.

## Your Solution(s)

The slug will have to be additionally stored in the config to keep the process network free.

**Comment by ok-coder1** [comment]
Please close?
#462
