### ISSUE TITLE
Lock/pin a mod/modpack to a specific version

### ISSUE THREAD

**Issue by uzervlad** [gorilla-devs/ferium#82]
I have encountered an issue when installing [GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib) for Fabric. Authors provide releases for Quilt on CurseForge, but are forced to tag them as Fabric, since Quilt is not yet supported there.
![image](https://user-images.githubusercontent.com/24654479/168632906-c321e635-0a77-418f-bcbb-fdd819c318b2.png)

---
# Tasks

- [x] Store pin data in the config
- [x] Use pin data in version resolution
- [x] Implement adding pinned mods
- [ ] Pin/unpin subcommands

**Comment by HellishINC** [comment]
Another example of this being useful is sticking to a stable version. Currently upgrading will upgrade to beta or alpha versions if available.

Currently JEI stable is "jei-1.18.2-9.7.0.209". Issuing an upgrade will grab the current alpha version (jei-1.18.2-forge-10.1.1.231) which is heavily stripped down (it removed the ability to configure client side options among many other things for example) which is also currently crashing forge.

**Comment by BilElSicario** [comment]
Do you plan on adding that feature any soon ?

**Comment by theRookieCoder** [comment]
Unfortunately, I have some important exams coming up. They'll end in March so I have to put my programming on hold for now :(

**Comment by BilElSicario** [comment]
> 

Same ! Wish you do well in those exams :)

**Comment by theRookieCoder** [comment]
Thanks, same to you!

**Comment by joeyak** [comment]
Any update on if this is planned? I'll be starting a server soon, and I want to pin client side mods (specifically simple voice chat) but allow mods like lithium to update.

**Comment by iamkarlson** [comment]
JEI broke stuff again, is there a way to pin a version?

**Comment by danielwerg** [comment]
I had an issue with [Concurrent Chunk Management Engine](https://modrinth.com/mod/c2me-fabric/versions)  `0.3.6+alpha.0.18+25w45a` version, c2m devs forgot to add `Game version` field and ferium was downloading it instead of `1.21.10` version, it is fixed now. Not exactly the same issue but I thought it wasn't worth opening new one.
